### ISSUE TITLE
Connect4 todo

### ISSUE THREAD

**Issue by cchudant** [SkyBeastMC/shiro#1]
- [x] Board full check
- [x] Better error handling
- [ ] Game leave command
- [ ] Move timeout
- [ ] Configurable messages
- [ ] Control with reactions
- [ ] Delete old board message
- [ ] Timedelete "Please send a number between 1 and 7." messages
- [ ] More configuration
- [ ] Connection message says who joined
- [x] Use migi discord error embeds
- [ ] Think about player order
- [ ] Leaderboard?
- [ ] Change leave / join commands
